### ISSUE TITLE
Verifier API Task Breakdown

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1093]
**Is your feature request related to a problem? Please describe.**

The [Epic Labs API](https://github.com/livepeer/verification-classifier/tree/master/api) needs to be integrated into go-livepeer in order to gather real world data on the verification process.

**Describe the solution you'd like**

### Phase 1 : API Integration

Most of these have been implemented within https://github.com/livepeer/go-livepeer/pull/1096

- [x] Add API address CLI flag
  * Will this flag be subject to change once the full policy implementation complete?
  * Do we ship testnet / mainnet with a default verifier API address (eg, Livepeer operated)?
- [x] API type flag ( ? )
  * Built into the API address itself, eg `-epicVerifier http://localhost:port/classifier`
  * Could be built into the address scheme itself, eg `-verifierAddr epic://localhost:port/classifier`
      * May be difficult to distinguish protocol, eg HTTP vs HTTPS
  * Flag for a policy file can also define the type, eg `-verificationPolicy /path/to/policy/file` with CLI flags for each policy option, including the URL
- [x] Define interface for verifier + policy + API parameters
  * Sketch out compatibility with a couple verifier implementations
  * Epic Labs and one other (eg, coersion or an hypothetical SSIM verifier)
- [x] Implement call-out to Epic Labs API
  * Prior to inserting in HLS playlist
  * Only if on-chain *and* a verifier address is specified via CLI
  * Error case from verifier will result in a drop for now - can be configured via policy later.
- [ ] Clean up surrounding code as necessary (eg, remove pixel counting)
- [x] Update documentation on flags / API usage

### Phase 2 : Results Interpretation and Policy Enforcement

Most of these items need further design / spec work but the broad outlines are as following:

- [x] Define policy defaults for verification classifier: https://github.com/livepeer/verification-classifier/issues/61
- [x] Check audio MD5 hash within verifier : https://github.com/livepeer/verification-classifier/issues/60
- [x] Policy implementation in go-livepeer with sequential retries : https://github.com/livepeer/go-livepeer/pull/1096
- [ ] Parallel implementation of retries
- [ ] Ban Policy : https://github.com/livepeer/go-livepeer/issues/1100#issuecomment-558714000

### Phase 3: Dynamic Policies

We might have to consider mid-stream changes to various policy parameters if we detect that the threshold is set too high for a given content, or we may want to adjust the sampling rate based on history or risk tolerance, and so forth.

**Comment by yondonfu** [comment]
> Do we ship testnet / mainnet with a default verifier API address (eg, Livepeer operated)?

I like the idea of defaulting to a publicly hosted verifier, but first we should consider the implications of securing, maintaining uptime for and scaling a public verifier in the short term - that discussion can happen separately from this task breakdown though.

> API type flag 

Do we need to specify the API type if we standardize the API params + request + response format? We could rename the `tamper` field in the response to `score` - how the score is calculated would be an implementation detail of the verifier. Then, an additional flag(s) could be used (if not used there would be some defaults) to specify the policy. Some options include:

- A `-verificationPolicy` flag that accepts a JSON file that specifies the policy
- `-verificationPolicyMinScore` and `-verificationPolicyMaxRetries` flags to specify policy params separately

> an hypothetical SSIM verifier

When we eventually move to directly measuring quality instead of just focusing on content tampering, we might have to consider changes to the policy implementation if the acceptable score threshold varies depending on the source content leading to always using the max retries for certain types of content. 

>  Implement call-out to Epic Labs API

We'll need an error handling path in case the broadcaster doesn't receive a response from the API. The safe thing to do is probably to drop the segment, but this hurts the streaming experience.

> Prior to inserting in HLS playlist (?)

I do think we should verify before inserting into the playlist for now to provide stronger guarantees for no tampering when running in on-chain mode on the public network.

**Comment by j0sh** [comment]
Thanks @yondonfu , updated the main writeup with some of your notes.

> Do we need to specify the API type if we standardize the API params + request + response format?

Possibly we can standardize the request. I'm not so sure about the response though, because I expect the response (and the composition of any associated policy) to vary based on the verifier in use.

For example, while the current classifier returns a single `tamper` score, a SSIM verifier might actually return the SSIM scores of each frame, with the policy built for that. A SSIM policy might then say something like, “90% of frames should be within 0.95 of original, with no frames under 0.7” which implies at least three or four parameters within the policy. (We'll naturally need to define an ordering for SSIM scores; something like the mean or median score of all frames could be used.)

>> API type flag
>
> A -verificationPolicy flag that accepts a JSON file that specifies the policy
> -verificationPolicyMinScore and -verificationPolicyMaxRetries flags to specify policy params separately

That would be one way to specify the API type, yes. If each policy parameter also has its own associated CLI flag, then the verifier address could just be considered part of the policy file itself, and overridable via CLI. Something like:

```ini
[Policy]
Name = epicClassifier

# URL can be blank by default; needs to be specified via CLI
# Or the user can supply their own verifier here (or we default to our own)
# URL = http://some/address

minScore = 0
maxRetries = 3
samplingRate = 0.33
parallelRetries = false

```

The associated flags can look something like this: `-verificationPolicy /path/to/epicClassifier.toml -epicClassifier.URL = http://localhost:5000/verify`

Of course, the actual naming / format of the flags themselves are open for discussion. 

(Nit: I'm of the opinion that JSON is a poor choice for a configuration format. Something ini-like is much more readable (eg, toml), less boilerplate-y and actually supports niceties like comments.)

> The safe thing to do is probably to drop the segment

This could also probably be configured via policy. We can drop for now until Phase 2. Updated the writeup to reflect this.

>  we might have to consider changes to the policy implementation if the acceptable score threshold varies depending on the source content leading to always using the max retries for certain types of content.

Absolutely - I was thinking those sort of "dynamic policies" could be a Phase 3 item after we have the basic, static policy implementation in. Updated the writeup to reflect this.

Relatedly, I've also been wondering if the current classifier is susceptible this (eg, showing higher FPR/FNR rates based on content type), and 
 alluded to the question in https://github.com/livepeer/verification-classifier/issues/61#issue-494436592 .

**Comment by yondonfu** [comment]
> a SSIM verifier might actually return the SSIM scores of each frame, with the policy built for that

Right I guess it'll depend on the actual SSIM implementation. I believe there is a variant where scores are calculated for all frames and then averaging of scores is weighted based on motion between consecutive frames (from [pixel based metrics section of this article](https://medium.com/@eyevinntechnology/video-quality-assessment-34abd35f96c0) referencing [this paper](https://live.ece.utexas.edu/publications/2004/zwang_vssim_spim_2004.pdf)). Using such a variant would simplify the policy since we can stick with assuming a single continuous score. But there could still be other methods that wouldn't fit this single continuous score framework though.

> Something ini-like is much more readable (eg, toml), less boilerplate-y and actually supports niceties like comments

I agree 😄

**Comment by ndujar** [comment]
> a SSIM verifier might actually return the SSIM scores of each frame, with the policy built for that

>Right I guess it'll depend on the actual SSIM implementation. I believe there is a variant where scores are calculated for all frames and then averaging of scores is weighted based on motion between consecutive frames (from pixel based metrics section of this article referencing this paper). Using such a variant would simplify the policy since we can stick with assuming a single continuous score. But there could still be other methods that wouldn't fit this single continuous score framework though.

After some thought, if the purpose of a quality metric is to help in the evaluation of performance of a number of orchestrators, the average value on a per-frame basis may as well do the job, provided that it is objectively the same for all of them and the bitrate is the same.
With the current implementation, outputting SSIM and PSNR is quite straightforward. Those metrics are included in the video_metrics module and computing them wouldn't mean a huge overhead in processing time given that the decoding and frame conversion to numpy array would have already been done.
That being said, in order to "activate" those metrics they need to be included in the metrics_list that is passed to the video_asset_processor as argument. Currently this list is directly extracted from the one used to train the model (which doesn't include them).

**Comment by ndujar** [comment]
I have added a new issue in this respect [here](https://app.zenhub.com/workspaces/transcoding-verification-5ce878fbf542de6fd8ff749b/issues/livepeer/verification-classifier/66)
