### ISSUE TITLE
Update active set tracking

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1123]
**Is your feature request related to a problem? Please describe.**

Note: The contracts still use the term "transcoders". Transcoders within the contracts correspond to orchestrators outside of the contracts.

In the latest version of the contracts, the state of the on-chain active set is tracked in the following way:

- An on-chain pool with a fixed max size is used to keep track of which orchestrators to activate/deactivate
- When an orchestrator is added to the on-chain pool, its `activationRound` is set to `currentRound + 1` and a `TranscoderActivated` event is emitted
- When an orchestrator is removed from the on-chain pool, its `deactivationRound` is set to `currentRound + 1` and a `TranscoderDeactivated` event is emitted
- An orchestrator is active in the `currentRound` if `activationRound <= currentRound < deactivationRound`
- The active set for the `currentRound` consists of all orchestrators that satisfy the above condition in the `currentRound`

Unlike in the old version of the contracts, the on-chain pool in the new version of the contracts does not necessarily reflect the state of the active set in a round. If an orchestrator is removed from the pool in the current round, the orchestrator will remain in the active set until the end of the round. If an orchestrator is added to the pool in the current round, the orchestrator will not be in the active set until the next round.

Given these changes to the way the state of the active set is tracked in the contracts, the node also an updated strategy for tracking the active set.

**Describe the solution you'd like**

The node can watch for `TranscoderActivated` and `TranscoderDeactivated` events emitted from the BondingManager contract to updates its view of the active set. A rough sketch of the steps to accomplish this (just a high level overview - implementation details omitted) are:

- [ ] Update the DB schema for the orchestrators table to include `activationRound` and `deactivationRound`
- [ ] Add a `CurrentRound` field to `DBOrchFilter`. If this field is populated, only active orchestrators in `CurrentRound` should be returned
- [ ] Update the `db.SelectOrchs()` query to only fetch active orchestrators in `CurrentRound` if the `DBOrchFilter.CurrentRound` is populated
- [ ] Create an event watcher that watches for `TranscoderActivated` and `TranscoderDeactivated` events from the BondingManager contract and update the corresponding orchestrator table entries accordingly with the address' current `activationRound` and `deactivationRound` values. We likely want to cache the serviceURI for an address when we see the `TranscoderActivated` event
- [ ] Either use the same event watcher as above or create a new event watcher that watches for `ServiceURIUpdate` events and updates serviceURIs stored in the DB. We only care about orchestrators that we are aware of (i.e. orchestrators in DB)
- [ ] Remove the call to `RegisteredTranscoders()` in `DBOrchestratorPoolCache` that fetches the members of the on-chain pool since the event watcher for activation/deactivation events should populate the DB with orchestrator addresses. Instead, we can just query for a list of active orchestrators from the DB. We can also keep the code that calls `GetOrchestrator()` on each of the orchestrators since we need off-chain prices though
- [ ] Update `blockwatch.Watcher` to be able to backfill from a specified block in the past. At the moment, it will only backfill past events if it has seen a block before (i.e. if it has started watching previously). It will not backfill past events if the node is starting for the first time. When the node is starting for the first time, we can have the node backfill past events starting from the block when the contracts were first deployed (on Rinkeby/mainnet this would be the block when the contracts were upgraded)

**Comment by yondonfu** [comment]
One thing to note re: updating the DB schema for the orchestrators table:

This would be a backwards incompatible change since old DB versions will not have the `activationRound` and `deactivationRound` columns which are necessary for checking if an orchestrator is active in the current round. While we are planning on cutting releases regularly for the SF public testnet, since we're still in the testnet phase and in a fast moving development cycle I think it's still ok to hold off on implementing DB migrations until we cut a mainnet release and for now just inform users that they should create a new DB whenever a release includes backwards incompatible DB schema changes.
