### ISSUE TITLE
PR Checklist

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#602]
**Is your feature request related to a problem? Please describe.**
We could do a better job of nudging each other to update tests and documentation when a PR is submitted.

**Describe the solution you'd like**
LivepeerJS sets a good example here with its checklist. Something similar could work here, eg:
- [ ] Tests added and/or fixed
- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv

**Comment by ericxtang** [comment]
Created a [pull request template](https://github.com/livepeer/go-livepeer/blob/master/PULL_REQUEST_TEMPLATE.md)
