### ISSUE TITLE
Streamflow migration path

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#969]
There have been a number of backwards incompatible changes since the last go-livepeer release. To ease the transition for our current users (especially orchestrators), we need to develop and communicate a migration path prior to the mainnet Streamflow release.

Some considerations include:

* [x] Database migration. Might be as simple as using a new DB file by default (eg, `lpdb2.sqlite`) https://github.com/livepeer/go-livepeer/issues/1286
* [ ] Document all flags throughly https://github.com/livepeer/go-livepeer/issues/708
* [x] Describe the flag changes that are needed to support Streamflow (mapping from old to new, and any additional flags such as pricing) https://github.com/livepeer/docs/pull/51
* [ ] Review and update external documentation such as readthedocs
* [x] Prevent datadir reuse https://github.com/livepeer/go-livepeer/issues/1098
* [x] Check for unsupported networks https://github.com/livepeer/go-livepeer/issues/1092
